#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Copyright 2014 cloudControl GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from cctrl.settings import Settings
from cctrl.app_commands import setup_cli


if __name__ == "__main__":
    settings = Settings(api_url='https://api.app.exo.io', token_source_url="https://portal.exoscale.ch/api/apps/token",
                        ssh_forwarder_url='sshforwarder.app.exo.io')
    setup_cli(settings)
